### ISSUE TITLE
Silly question

### ISSUE THREAD

**Issue by qualquercoisakk** [acuifex/acuion#14]
I have a doubt, the hitchance feature try to calculate the chance of hit that shot or its like a error margin?
example if you choose 60% you only have this chance of hit or just will shot if have this chance?

**Comment by acuifex** [comment]
it works like spread limit. if your chance to hit is less than set in settings it simply will not shoot.

**Comment by acuifex** [comment]
i'm gonna guess i answered your question so i'm going clone this issue. feel free to ask more questions.
