### ISSUE TITLE
Spammer crashing

### ISSUE THREAD

**Issue by audadhf** [acuifex/acuion#15]
hey buddy thanks for anwser that question, but this time im having a issue when i enable spammer kills and when i kill someone the game freeze

i use Fedora

(gdb) backtrace
#0  0x00007fbb937324a9 in Spammer::BeginFrame (frameTime=<optimized out>)
    at /usr/include/c++/10/bits/stl_vector.h:1043
#1  0x00007fbb9373784d in Hooks::BeginFrame (thisptr=0x7fbbe8312ba0, 
    frameTime=0.00631800015)
    at /home/eu/Programas/CSGOHacks/Fuzion/src/Hooks/BeginFrame.cpp:20
#2  0x00007fbbeda1b47a in ?? ()
   from /home/eu/.local/share/Steam/steamapps/common/Counter-Strike Global Offensive/bin/linux64/engine_client.so
#3  0x00007fbbedb51be4 in ?? ()
   from /home/eu/.local/share/Steam/steamapps/common/Counter-Strike Global Offensive/bin/linux64/engine_client.so
#4  0x00007fbbedb539b5 in ?? ()
   from /home/eu/.local/share/Steam/steamapps/common/Counter-Strike Global Offensive/bin/linux64/engine_client.so
#5  0x00007fbbedb61bd5 in ?? ()
   from /home/eu/.local/share/Steam/steamapps/common/Counter-Strike Global Offensive/bin/linux64/engine_client.so
#6  0x00007fbbedb62084 in ?? ()
   from /home/eu/.local/share/Steam/steamapps/common/Counter-Strike Global Offensive/bin/linux64/engine_client.so
#7  0x00007fbbedbe06e2 in ?? ()
   from /home/eu/.local/share/Steam/steamapps/common/Counter-Strike Global Offensive/bin/linux64/engine_client.so

**Comment by acuifex** [comment]
does it happen with fuzion?
i'm gonna guess GetPlayerInfo offset got updated but i can't say much because backtrace isn't very informative. 
ask lwss at fuzion page about this. i have not changed spammer in any way.

**Comment by audadhf** [comment]
Yes, with fuzion and acuion
i will ask there
thx

**Comment by acuifex** [comment]
i'm not strong with reverse engineering. closing due to not my problem xd
