### ISSUE TITLE
Game crashes

### ISSUE THREAD

**Issue by scclie** [acuifex/acuion#26]
After the cheat injection, the game crashes. I tried reinstalling acuion, but it doesn't help. With Fusion, there are no such problems. A few days ago everything was working fine

**Comment by acuifex** [comment]
Just merge changes from fuzion. I'll do that tomorrow

**Comment by SuperGamingBros4** [comment]
you can just copy the sdlhook.cpp file from fuzion and replace the file in acuion and run "sudo ./build"(without the quotes) in the acuion folder and fix it.

**Comment by acuifex** [comment]
should be working now.



> you can just copy the sdlhook.cpp file from fuzion and replace the file in acuion and run "sudo ./build"(without the quotes) in the acuion folder and fix it.

That is generally a bad idea. this can fuckup stuff.

**Comment by SuperGamingBros4** [comment]
It worked just fine for me with no errors anywhere
