### ISSUE TITLE
steam linux runtime support?

### ISSUE THREAD

**Issue by AndreasYNY** [acuifex/acuion#28]
some arch based system have problems with proton and csgo wont launch. that's too bad because fuzion is proton based..is there any way to make fuzion works with runtime?

**Comment by JuniorJPDJ** [comment]
....what?
fuzion runs on linux port of csgo, you cant even run csgo on proton as it's native

**Comment by AndreasYNY** [comment]
I've tested this on arch & manjaro, both of them can't run csgo on proton, but it can run csgo on runtime... some people just ignore this and use runtime.
but ubuntu/pop is working just fine...
![image](https://user-images.githubusercontent.com/46004308/110738403-cdbbaf00-8261-11eb-99d5-fe6e4bd73513.png)

**Comment by AndreasYNY** [comment]
i tried to inject fuzion on runtime, and it just crash.

**Comment by JuniorJPDJ** [comment]
There's solution on your crashes: https://github.com/LWSS/Fuzion/issues/621#issuecomment-777844878

CSGO shouldn't run in Proton.

**Comment by AndreasYNY** [comment]
![image](https://user-images.githubusercontent.com/46004308/110841784-edda8500-82d8-11eb-9ed7-525531b8bf4a.png)
i've tried it...still not working....

**Comment by acuifex** [comment]
i still don't understand what you're trying to accomplish. explain what are you exactly doing/pressing and what exactly it is not doing as you expect? also `./build-debug` and `./debug`

edit:
> you cant even run csgo on proton as it's native

you can force proton on any game

**Comment by AndreasYNY** [comment]
yes, so i'm trying to inject acuion on arch system. usually  i run csgo under proton on ubuntu and it work just fine. but when i move to arch csgo won't work with proton. instead it works under linux runtime...and wnow i can't inject acuion because of it...is there any way to do it?

debug: https://pastebin.com/37LyenMH

**Comment by acuifex** [comment]
`warning: Expected absolute pathname for libpthread in the inferior, but got target:/overrides/lib/x86_64-linux-gnu/libpthread.so.0.`
looks like arch gdb problem. Have you tried solutions at https://github.com/LWSS/Fuzion/issues/621 ?

```
$1 = (void *) 0x0
(gdb) 
```
first, you have to continue here a few times
second, it points to null so it means your cheat library didn't inject. that looks like an arch gdb problem.

also cheat doesn't work under proton or any sandbox (firejail, snap, flatpak, etc) so you have to run it natively.

edit: you have to disable forced use of proton. i have no idea what is steam linux runtime in there

**Comment by AndreasYNY** [comment]
sorry for late reply. just tested it, option number 2 is working! thanks!

**Comment by JuniorJPDJ** [comment]
It's cool you clicked the link and it fixes problem as I already sent it to you >__<
