### ISSUE TITLE
New update for operation riptide completely breaks the cheat.

### ISSUE THREAD

**Issue by AdverseMiller** [acuifex/acuion#30]
The newly released operation riptide will cause the cheat to crash when using it in game. I've tried many different configs and even just having the cheat injected with no config selected will still cause the cheat to crash. I've noticed this to happen with multiple other AImtux based cheats.

**Comment by invakid404** [comment]
+1, experiencing this as well. CS:GO instantly crashes when joining a game.

**Comment by AdverseMiller** [comment]
I haven't noticed it to particularly crash while loading into game, but to instead crash while a new round starts.

**Comment by acuifex** [comment]
see gitter if you guys wanna be up to date, a bunch of patterns and indexes have been changed

**Comment by AdverseMiller** [comment]
can you send me a link to the gitter? I can't find it

**Comment by acuifex** [comment]
https://gitter.im/Aimtux-Fuzion/Lobby#

**Comment by acuifex** [comment]
just made a fix, https://github.com/acuifex/acuion/commit/cd63af4618f3bdef729891ceaeecc3839459d661
lmk if everything works

**Comment by AdverseMiller** [comment]
It works :)
