### ISSUE TITLE
Crashing on localplayer

### ISSUE THREAD

**Issue by dangerousNull** [acuifex/acuion#4]
Hello!

I know this issue is because acuion runs on an older version of Fuzion, but there has been a patch on CSGO, which crashes the game as soon as I would spawn.

Please merge with Fuzion.

**Comment by acuifex** [comment]
okay, i will update my fork later.
quick question: why do you use this fork? is it better at hvh or something?

ср, 2 окт. 2019 г., 7:45 Zedespook <notifications@github.com>:

**Comment by acuifex** [comment]
Have fun.
